### ISSUE TITLE
Like/Dislike menu action is broken with GPMDP 4.6.0+

### ISSUE THREAD

**Issue by darkvertex** [nbd9/vscode-gmusic#5]
I have `google-play-music-desktop-player-4.6.0-1.x86_64` installed and the extension's `GMusic: Like/Dislike Song` action isn't working.

It doesn't print or report any errors but nothing happens on the player side, except that when I check the terminal I launched it from, I saw:

```
error: WebSocketAPI Error: Invalid message recieved , data={"namespace":"rating","method":"setRating","arguments":5}
Error: Bad arguments
    at WebSocket.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app.asar/build/main/features/core/websocketAPI.js:197:17)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/WebSocket.js:841:10)
    at /usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:371:5)
    at /usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/usr/share/google-play-music-desktop-player/resources/app.asar/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
error: WebSocketAPI Error: Invalid message recieved , data={"namespace":"rating","method":"setRating","arguments":5}
```

It appears that the WebSocket API has changed slightly:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md#rating
as I don't see anything about `setRating` there.

**Comment by nbd9** [comment]
Thanks for the bug report! Sorry for the delay - I actually have moved on to another music streaming service. The command _shouldn't_ have been the issue, as [setRating is a still accepted](https://github.com/gmusic-utils/gmusic.js#ratingsetratingrating) (i.e. why it worked in playlists).

Nonetheless, 5141ac90c08443d4adac0c0dfe2385f254ea947d should have fixed it.

**Comment by darkvertex** [comment]
Thank you. What music streaming service did you switch to, out of curiosity? Spotify? YouTube Music?

**Comment by nbd9** [comment]
Spotify. Their student deal pulled me from Google Play Music.
